# Generated by Django 5.0.3 on 2024-04-08 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.CharField(max_length=123)),
                ('tg_id', models.CharField(max_length=123, unique=True)),
                ('username', models.CharField(max_length=123)),
                ('tg_phone', models.CharField(max_length=123, unique=True)),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram',
            },
        ),
    ]
